import LocalizedStrings from 'react-native-localization';

export default new LocalizedStrings({
 	en:{
 		slogan: "Let's Learn Chinese",
 		preferredLanguage: '华文',
   		login: 'Login',
   		username: 'Username',
   		password: 'Password',
   		forgetPassword: 'Forgotten Your Password?',
   		or: 'Or',
   		joinNow: 'Join Us Now!',
   		lesson1: 'Lesson 1',
     	lesson2: 'Lesson 2',
   		lesson3: 'Lesson 3',
     	lesson4: 'Lesson 4',
     	lesson5: 'Lesson 5',
   		lesson6: 'Lesson 6',
     	lesson7: 'Lesson 7',
   		lesson8: 'Lesson 8',
     	lesson9: 'Lesson 9',
     	lesson10: 'Lesson 10',
     	term1: 'Term 1',
     	term2: 'Term 2',
     	term3: 'Term 3',
     	term4: 'Term 4',
     	learnTo: 'Learn to',
     	read: 'Read',
     	write: 'Write',
     	pinyin: 'PinYin',
 	},
 	"zh-CN": {
 		slogan: '来学中文吧',
 		preferredLanguage: 'Eng',
	   	login: '登录',
	   	username: '用户名',
	   	password: '密码',
	   	forgetPassword: '忘记密码',
	   	or: '或',
	   	joinNow: '立刻加入!',
	   	lesson1: '第一课',
	   	lesson2: '第二课',
	   	lesson3: '第三课',
	   	lesson4: '第四课',
	   	lesson5: '第五课',
	   	lesson6: '第六课',
	   	lesson7: '第七课',
	   	lesson8: '第八课',
	   	lesson9: '第九课',
	   	lesson10: '第十课',
	   	term1: '学期一',
	   	term2: '学期二',
	   	term3: '学期三',
	   	term4: '学期四',
	   	learnTo: '学',
     	read: '发音',
     	write: '写字',
     	pinyin: '拼音',
 	}
});